name: stroketriage-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - absl-py==2.2.2
    - astunparse==1.6.3
    - clarabel==0.10.0
    - contourpy==1.3.2
    - cvxpy==1.6.5
    - cycler==0.12.1
    - flatbuffers==25.2.10
    - fonttools==4.57.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.72.0
    - h5py==3.13.0
    - imbalanced-learn==0.13.0
    - keras==3.9.2
    - matplotlib==3.10.1
    - ml_dtypes==0.5.1
    - numpy==1.26.4
    - opt_einsum==3.4.0
    - optuna==4.3.0
    - osqp==1.0.3
    - pandas==2.2.3
    - pillow==11.2.1
    - openpyxl
    - pyarrow==20.0.0
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - setuptools==75.8.0
    - shap==0.47.2
    - statsmodels==0.14.5
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.19.0
    - termcolor==3.0.1
    - xgboost==3.0.0
variables:
  PYTHONHASHSEED: '0'